info:
  app:
    profiles: dev
    name: eureka-server #从pom.xml中获取
    description: eureka-server
spring:
  application:
    name: eureka-server # 实例的名称
  profiles:
    active: dev
server:
  port: 10002
  tomcat:
      uri-encoding: utf-8
# 健康检查的配置
management:
  health:
    mail:
      enabled: false
    redis:
      enabled: false
  security:
    enabled: false #springbooot1.5.*以后如果要使用refresh功能的要设置false
  port: 10003
security:
  basic:
    enabled: false
  user:
    name: micro
    password: fast
# 日志配置
logging:
  config: classpath:log4j2-dev.xml
springfox:
  documentation:
    swagger:
      v2:
        path: /api/api-doc